サインイン機能を追加
OCS-GEEK-HACK/campus-tech-forum pull request #9
Opened 2024-12-19 16:29 UTC by syun17

Closes # 1

## 概要

## 変更点

## 追加情報

2024-12-19 22:43 UTC, illionillion commented
Closes #1

正しくはこう

それとレビュワーに自分を設定して。

2024-12-19 23:20 UTC, illionillion requested changes
@syun17 

サインインフォームの修正をお願いします。
一度サインインするとサインイン画面に戻れなくなるので、サインアウトも実装してください。
未サインイン時状態は`/`や他ページを見た時にセッションを確認して`/signin`に戻るようにもしてください。

実装は参考用リポジトリに全部書いてあります。

2024-12-19 23:20 UTC, illionillion commented on php/www/auth/index.php
> +<body>
画面幅いっぱいにする。

```suggestion
<body class="vh-100">
```

2024-12-19 23:20 UTC, illionillion commented on php/www/auth/index.php
> +    <div class="container mt-5 w-50">
`m-5`で上部から固定値で中央に寄せようとしない、`w-50`だとモバイル時に崩れるので消す。
`container`で`max-width`がついてるのでそれで十分。

```suggestion
    <div class="container  h-100 d-flex justify-content-center align-items-center">
```

2024-12-19 23:20 UTC, illionillion commented on php/www/auth/index.php
`before / after`
<img width="208" alt="image" src="https://github.com/user-attachments/assets/c4b7e484-dbc7-4792-97d2-8f923bb928db" /> <img width="210" alt="image" src="https://github.com/user-attachments/assets/4ac6c6ba-21ee-4192-a7e7-58f1d3cbd071" />

サインアップのURLはどういう想定でしていた？
サインインを`/auth/index.php`にするよりも`/auth/signin/index.php`か`/signin/index.php`の方が、サインアップも`/auth/signup/index.php`にして揃えれると思う。

2024-12-20 03:29 UTC, syun17 commented on php/www/auth/index.php
全く別のフォルダーを作る予定でした。
サインアップも揃えるために/auth/signin/index.phpに変えておきます。

2024-12-20 04:08 UTC, illionillion requested changes
@syun17 

ログアウトのボタンのリンクを`/actions/signout.php`に変えるのを忘れてる。

2024-12-20 04:08 UTC, illionillion commented on php/www/auth/signout/index.php
なくても良いのでは？

2024-12-20 04:08 UTC, illionillion commented on php/www/event/index.php
> +}
元のリポジトリでどうなってたか確認してほしい。
全部のページに直書きするのでなく１つのファイルにまとめてたのを`require`してたはず。

2024-12-20 04:41 UTC, illionillion approved these changes

2024-12-20 04:41 UTC, merged